version: "3.8"

services:
  data:
    image: mariadb
    container_name: data
    networks:
      - tp3
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  script:
    build: ./src
    container_name: script
    networks:
      - tp3
    volumes:
      - ./src:/app

  http:
    image: nginx
    container_name: http
    networks:
      - tp3
    ports:
      - "8080:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/app

networks:
  tp3:
    driver: bridge
